CREATE TABLE PRODUCT_COLOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_COLOR INT NOT NULL,
    ID_PRODUCT INT NOT NULL,
    FOREIGN KEY (ID_COLOR) REFERENCES COLOR(ID),
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID)
)