CREATE TABLE PRODUCT_SIZE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_SIZE INT NOT NULL,
    ID_PRODUCT INT NOT NULL,
    FOREIGN KEY (ID_SIZE) REFERENCES SIZE(ID),
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID)
)