CREATE TABLE PURCHASE_PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT INT NOT NULL,
    ID_PRODUCT INT NOT NULL,
    ID_COLOR INT NOT NULL,
    ID_SIZE INT NOT NULL,
    FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID),
    FOREIGN KEY (ID_COLOR) REFERENCES COLOR(ID),
    FOREIGN KEY (ID_SIZE) REFERENCES SIZE(ID)
)